"""phase 7 search history

Revision ID: 1aa5f6856263
Revises: a1c7e9b20d44
Create Date: 2026-08-26 02:25:45.255503
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1aa5f6856263'
down_revision: Union[str, None] = 'a1c7e9b20d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.String(length=512), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_search_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_history'))
    )
    op.create_index('ix_search_history_user_created', 'search_history', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search_history_user_created', table_name='search_history')
    op.drop_table('search_history')
    # ### end Alembic commands ###
